version: 2
jobs:
  build:
    docker:
      - image: 'python:3.7.3-stretch'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: >
            python3 -m venv ~/.app
            source /app/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./app
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            source /app/bin/activate
            make lint           
